#!/usr/bin/Rscript



# This script aggregates allelic repeat lengths from VCF files generated by
# ExpansionHunter. All of the VCF files should have been generated using
# the same variant catalogue.
#
# By Shahryar Alavi
# University of Isfahan, Isfahan, Iran
# UCL Institute of Neurology, London, UK
# December 2025



# Define the inputs below, then run the code
# ==================================================
# Working directory:
directory.working <- "/path/to/working/directory"

# ExpansionHunter VCF files directory:
dir.inputs <- paste0(directory.working, "/EH")

# Directory where to save analysis output:
dir.outputs <- paste0(directory.working, "/output")

dir.outputs.stats <- paste0(directory.working, "/stats")

# Number of EH variant lines plus the header:
nlines.variants <- 736
# ==================================================
# This loads the VCF files within the input directory, collects STRs genotypes, and saves a TSV file in the output directory.

# Dataframe for statistical analyses:
df.AllelicRepeats.cohort <- data.frame()

# Load the VCF files in a loop and process them
for (sampleVCF in list.files(path = dir.inputs, pattern = "*.vcf", full.names = TRUE)) {
  # Retrieve sample name:
  name.sample <- basename(sampleVCF)
  
  # Load the ExpansionHunter VCF file:
  nline.vcf <- length(readLines(sampleVCF))
  nlines.skip <- nline.vcf - nlines.variants
  vcf.sample <- read.csv(sampleVCF, header = TRUE, sep = "\t", skip = nlines.skip)
  
  # Retrieve repeat counts:
  genotype.info <- t(as.data.frame(strsplit(vcf.sample[, 10], ":")))
  repeat.count <- as.data.frame(t(as.data.frame(strsplit(genotype.info[, 3], "/"))))
  
  # Assign sample name to the column names:
  sample.allele1 <- paste0(name.sample, "-A1")
  sample.allele2 <- paste0(name.sample, "-A2")
  rownames(repeat.count) <- NULL
  colnames(repeat.count) <- c(sample.allele1, sample.allele2)
  repeat.count[] <- lapply(repeat.count, as.integer)
  
  # Create the list of STR loci:
  if (nrow(df.AllelicRepeats.cohort) == 0) {
    df.AllelicRepeats.cohort <- vcf.sample[, 1:2]
    df.AllelicRepeats.cohort <- cbind(df.AllelicRepeats.cohort, as.data.frame(tstrsplit(vcf.sample[, 8], ";", keep = c(1, 2, 4, 5))))
    colnames(df.AllelicRepeats.cohort) <- c("CHROM", "START", "END", "REF", "MOTIF", "GENE")
    df.AllelicRepeats.cohort$MOTIF <- gsub("RU=", "", df.AllelicRepeats.cohort$MOTIF)
    df.AllelicRepeats.cohort$END <- gsub("END=", "", df.AllelicRepeats.cohort$END)
    df.AllelicRepeats.cohort$REF <- gsub("REF=", "", df.AllelicRepeats.cohort$REF)
    df.AllelicRepeats.cohort$GENE <- gsub("VARID=", "", df.AllelicRepeats.cohort$GENE)
  }
  
  # Add allelic STR length:
  df.AllelicRepeats.cohort <- cbind(df.AllelicRepeats.cohort, repeat.count)
}

# Statistical analysis:
df.stats.STRs <- data.frame(Minimum = apply(df.AllelicRepeats.cohort[, -c(1:6)], 1, min, na.rm = TRUE), 
                            Maximum = apply(df.AllelicRepeats.cohort[, -c(1:6)], 1, max, na.rm = TRUE),
                            Median = apply(df.AllelicRepeats.cohort[, -c(1:6)], 1, median, na.rm = TRUE),
                            SD = apply(df.AllelicRepeats.cohort[, -c(1:6)], 1, sd, na.rm = TRUE),
                            Mean = apply(df.AllelicRepeats.cohort[, -c(1:6)], 1, mean, na.rm = TRUE),
                            NAfraction = apply(is.na(df.AllelicRepeats.cohort[, -c(1:6)]), 1, mean, na.rm = FALSE)
                            )

# Merge statistics with the genotype table
df.AllelicRepeats.cohort.stats <- cbind(df.AllelicRepeats.cohort, df.stats.STRs)

# Cleanup the statistics
order.column <- c("CHROM", "START", "END", "MOTIF", "REF", "GENE", "Minimum", "Maximum", "Median", "SD", "Mean", "NAfraction")
df.AllelicRepeats.cohort.ordered.temp <- df.AllelicRepeats.cohort.stats[, c(order.column)]
df.AllelicRepeats.cohort.ordered <- cbind(df.AllelicRepeats.cohort.ordered.temp, df.AllelicRepeats.cohort.stats[ , -which(names(df.AllelicRepeats.cohort.stats) %in% order.column)])

# Doing some more analysis:
df.STRs.statistics <- df.AllelicRepeats.cohort.ordered[, 1:12]
# Calculate the difference of STR sizes in my population compared to the reference genome:
df.STRs.statistics$CNV <- as.integer(df.STRs.statistics$Median) - as.integer(df.STRs.statistics$REF)

# Save the statistics as R objects:
save(df.AllelicRepeats.cohort.ordered, df.STRs.statistics, file = paste0(dir.outputs.stats, "/allelic-repeats_stats.RData"))

# Save as tables as TSV files:
write.table(df.AllelicRepeats.cohort.ordered, paste0(dir.outputs.stats, "/STR_genotypes.tsv"), quote = FALSE, sep = "\t", row.names = FALSE)
write.table(df.STRs.statistics, paste0(dir.outputs.stats, "/STR_stats.tsv"), quote = FALSE, sep = "\t", row.names = FALSE)
